@startuml

autonumber

actor Пользователь
box Open Id Connect аутентификация
    participant Клиент
    participant Сервер_Авторизации
    participant Сервер_Ресурсов
end box

Пользователь -> Клиент: Вход через Google
Клиент --> Пользователь: Перенаправление на вход
Пользователь -> Сервер_Авторизации: Вход в систему
Сервер_Авторизации -> Сервер_Авторизации: Выбор учётной записи
Сервер_Авторизации -> Сервер_Авторизации: Подтверждение,приложение\nполучит доступ к профилю
Сервер_Авторизации --> Клиент: Предоставление кода авторизации
Клиент -> Сервер_Авторизации: Обмен кода авторизации
Сервер_Авторизации -> Клиент: Получение Access Token и ID token
Клиент -> Клиент: Получение данных о пользователе из ID token
Клиент -> Сервер_Ресурсов: Запрос дополнительных данных о пользователе через Access  token
Сервер_Ресурсов -> Клиент: Предоставление дополнительных данных о пользователе
Клиент -> Пользователь: Добро пожаловать, [фото + \nимя пользователя из аккаунта Google]

@enduml